// Sample product data
export const products = [
  {
    id: 1,
    name: "Fresh Bananas",
    nameAr: "موز طازج",
    category: "fruits",
    description: "High-quality fresh bananas. Rich in vitamins and minerals beneficial for the body.",
    descriptionAr: "موز طازج عالي الجودة. غني بالفيتامينات والمعادن المفيدة للجسم.",
    originalPrice: 30,
    discountedPrice: 21,
    discount: 30,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Carrefour",
    supermarketAr: "كارفور",
    expiryDate: "2023-07-25",
    featured: true,
    quantity: 1,
  },
  {
    id: 2,
    name: "Fresh Milk",
    nameAr: "حليب طازج",
    category: "dairy",
    description: "Fresh whole milk. An excellent source of calcium and protein.",
    descriptionAr: "حليب طازج كامل الدسم. مصدر ممتاز للكالسيوم والبروتين.",
    originalPrice: 25,
    discountedPrice: 15,
    discount: 40,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Spinneys",
    supermarketAr: "سبينيس",
    expiryDate: "2023-07-22",
    featured: false,
    quantity: 1,
  },
  {
    id: 3,
    name: "Multigrain Bread",
    nameAr: "خبز متعدد الحبوب",
    category: "bakery",
    description: "Fresh multigrain bread. Rich in fiber and vitamins.",
    descriptionAr: "خبز طازج متعدد الحبوب. غني بالألياف والفيتامينات.",
    originalPrice: 20,
    discountedPrice: 12,
    discount: 40,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "HyperOne",
    supermarketAr: "هايبر وان",
    expiryDate: "2023-07-21",
    featured: false,
    quantity: 1,
  },
  {
    id: 4,
    name: "Red Apples",
    nameAr: "تفاح أحمر",
    category: "fruits",
    description: "Fresh red apples. Rich in antioxidants and fiber.",
    descriptionAr: "تفاح أحمر طازج. غني بمضادات الأكسدة والألياف.",
    originalPrice: 40,
    discountedPrice: 28,
    discount: 30,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Carrefour",
    supermarketAr: "كارفور",
    expiryDate: "2023-07-26",
    featured: true,
    quantity: 1,
  },
  {
    id: 5,
    name: "Cheddar Cheese",
    nameAr: "جبن شيدر",
    category: "dairy",
    description: "High-quality cheddar cheese. Perfect for sandwiches and appetizers.",
    descriptionAr: "جبن شيدر عالي الجودة. مثالي للسندويشات والمقبلات.",
    originalPrice: 60,
    discountedPrice: 42,
    discount: 30,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Metro Market",
    supermarketAr: "مترو ماركت",
    expiryDate: "2023-07-23",
    featured: false,
    quantity: 1,
  },
  {
    id: 6,
    name: "Fresh Chicken",
    nameAr: "دجاج طازج",
    category: "meat",
    description: "High-quality fresh chicken. An excellent source of protein.",
    descriptionAr: "دجاج طازج عالي الجودة. مصدر ممتاز للبروتين.",
    originalPrice: 80,
    discountedPrice: 56,
    discount: 30,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "HyperOne",
    supermarketAr: "هايبر وان",
    expiryDate: "2023-07-22",
    featured: false,
    quantity: 1,
  },
  {
    id: 7,
    name: "Greek Yogurt",
    nameAr: "زبادي يوناني",
    category: "dairy",
    description: "High-protein Greek yogurt. Perfect for breakfast and snacks.",
    descriptionAr: "زبادي يوناني عالي البروتين. مثالي للفطور والوجبات الخفيفة.",
    originalPrice: 35,
    discountedPrice: 21,
    discount: 40,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Spinneys",
    supermarketAr: "سبينيس",
    expiryDate: "2023-07-23",
    featured: true,
    quantity: 1,
  },
  {
    id: 8,
    name: "Fresh Tomatoes",
    nameAr: "طماطم طازجة",
    category: "fruits",
    description: "High-quality fresh tomatoes. Rich in antioxidants and vitamins.",
    descriptionAr: "طماطم طازجة عالية الجودة. غنية بمضادات الأكسدة والفيتامينات.",
    originalPrice: 15,
    discountedPrice: 9,
    discount: 40,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Metro Market",
    supermarketAr: "مترو ماركت",
    expiryDate: "2023-07-24",
    featured: false,
    quantity: 1,
  },
]

// Categories
export const categories = [
  {
    id: "fruits",
    nameEn: "Fruits & Vegetables",
    nameAr: "فواكه وخضروات",
    icon: "🍎",
  },
  {
    id: "dairy",
    nameEn: "Dairy Products",
    nameAr: "منتجات الألبان",
    icon: "🥛",
  },
  {
    id: "bakery",
    nameEn: "Bakery",
    nameAr: "مخبوزات",
    icon: "🍞",
  },
  {
    id: "meat",
    nameEn: "Meat & Poultry",
    nameAr: "لحوم ودواجن",
    icon: "🥩",
  },
  {
    id: "canned",
    nameEn: "Canned Goods",
    nameAr: "معلبات",
    icon: "🥫",
  },
  {
    id: "snacks",
    nameEn: "Snacks",
    nameAr: "وجبات خفيفة",
    icon: "🍪",
  },
  {
    id: "beverages",
    nameEn: "Beverages",
    nameAr: "مشروبات",
    icon: "🥤",
  },
]
