// Helper function to generate random future dates after May 2025
function getRandomFutureDate() {
  // Start from May 1, 2025
  const startDate = new Date(2025, 4, 1).getTime()
  // End at December 31, 2026
  const endDate = new Date(2026, 11, 31).getTime()
  // Generate a random timestamp between these dates
  const randomTimestamp = startDate + Math.random() * (endDate - startDate)
  // Convert to date object
  const randomDate = new Date(randomTimestamp)
  // Format as YYYY-MM-DD
  return randomDate.toISOString().split("T")[0]
}

// Sample product data
export const products = [
  {
    id: 1,
    name: "Canned Tuna",
    nameAr: "تونة معلبة",
    category: "canned",
    description: "High-quality canned tuna in olive oil. Rich in protein and omega-3 fatty acids.",
    descriptionAr: "تونة معلبة عالية الجودة في زيت الزيتون. غنية بالبروتين وأحماض أوميغا 3 الدهنية.",
    originalPrice: 30,
    discountedPrice: 21,
    discount: 30,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "El Abd Market",
    supermarketAr: "سوبر ماركت العبد",
    expiryDate: getRandomFutureDate(),
    featured: true,
    quantity: 1,
  },
  {
    id: 2,
    name: "Fresh Milk",
    nameAr: "حليب طازج",
    category: "dairy",
    description: "Fresh whole milk. An excellent source of calcium and protein.",
    descriptionAr: "حليب طازج كامل الدسم. مصدر ممتاز للكالسيوم والبروتين.",
    originalPrice: 25,
    discountedPrice: 15,
    discount: 40,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "El Hussein Grocery",
    supermarketAr: "بقالة الحسين",
    expiryDate: getRandomFutureDate(),
    featured: false,
    quantity: 1,
  },
  {
    id: 3,
    name: "Potato Chips",
    nameAr: "شيبسي",
    category: "snacks",
    description: "Crunchy potato chips with salt. Perfect for snacking.",
    descriptionAr: "شيبسي مقرمش بالملح. مثالي للوجبات الخفيفة.",
    originalPrice: 20,
    discountedPrice: 12,
    discount: 40,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Mekka Mini Market",
    supermarketAr: "ميني ماركت مكة",
    expiryDate: getRandomFutureDate(),
    featured: false,
    quantity: 1,
  },
  {
    id: 4,
    name: "Orange Juice",
    nameAr: "عصير برتقال",
    category: "beverages",
    description: "Fresh orange juice. Rich in vitamin C and antioxidants.",
    descriptionAr: "عصير برتقال طازج. غني بفيتامين سي ومضادات الأكسدة.",
    originalPrice: 40,
    discountedPrice: 28,
    discount: 30,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "El Abd Market",
    supermarketAr: "سوبر ماركت العبد",
    expiryDate: getRandomFutureDate(),
    featured: true,
    quantity: 1,
  },
  {
    id: 5,
    name: "Cheddar Cheese",
    nameAr: "جبن شيدر",
    category: "dairy",
    description: "High-quality cheddar cheese. Perfect for sandwiches and appetizers.",
    descriptionAr: "جبن شيدر عالي الجودة. مثالي للسندويشات والمقبلات.",
    originalPrice: 60,
    discountedPrice: 42,
    discount: 30,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Zamalek Grocery",
    supermarketAr: "بقالة الزمالك",
    expiryDate: getRandomFutureDate(),
    featured: false,
    quantity: 1,
  },
  {
    id: 6,
    name: "Canned Beans",
    nameAr: "فول معلب",
    category: "canned",
    description: "Ready-to-eat canned fava beans. Traditional Egyptian breakfast.",
    descriptionAr: "فول معلب جاهز للأكل. فطور مصري تقليدي.",
    originalPrice: 15,
    discountedPrice: 10,
    discount: 33,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "El Hussein Grocery",
    supermarketAr: "بقالة الحسين",
    expiryDate: getRandomFutureDate(),
    featured: false,
    quantity: 1,
  },
  {
    id: 7,
    name: "Greek Yogurt",
    nameAr: "زبادي يوناني",
    category: "dairy",
    description: "High-protein Greek yogurt. Perfect for breakfast and snacks.",
    descriptionAr: "زبادي يوناني عالي البروتين. مثالي للفطور والوجبات الخفيفة.",
    originalPrice: 35,
    discountedPrice: 21,
    discount: 40,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Mekka Mini Market",
    supermarketAr: "ميني ماركت مكة",
    expiryDate: getRandomFutureDate(),
    featured: true,
    quantity: 1,
  },
  {
    id: 8,
    name: "Chocolate Cookies",
    nameAr: "بسكويت شوكولاتة",
    category: "snacks",
    description: "Delicious chocolate cookies. Great with tea or coffee.",
    descriptionAr: "بسكويت شوكولاتة لذيذ. رائع مع الشاي أو القهوة.",
    originalPrice: 25,
    discountedPrice: 15,
    discount: 40,
    image: "/placeholder.svg?height=300&width=300",
    supermarket: "Zamalek Grocery",
    supermarketAr: "بقالة الزمالك",
    expiryDate: getRandomFutureDate(),
    featured: false,
    quantity: 1,
  },
]

// Categories
export const categories = [
  {
    id: "canned",
    nameEn: "Canned Goods",
    nameAr: "معلبات",
    icon: "🥫",
  },
  {
    id: "dairy",
    nameEn: "Dairy Products",
    nameAr: "منتجات الألبان",
    icon: "🥛",
  },
  {
    id: "snacks",
    nameEn: "Snacks",
    nameAr: "وجبات خفيفة",
    icon: "🍪",
  },
  {
    id: "beverages",
    nameEn: "Beverages",
    nameAr: "مشروبات",
    icon: "🥤",
  },
]
